"""initial schema

Revision ID: 31316b8d8d5f
Revises: 
Create Date: 2025-11-02 11:30:03.124052

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '31316b8d8d5f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mood',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.CheckConstraint("category IN ('positive', 'negative', 'neutral')", name='check_mood_category'),
    sa.CheckConstraint('length(name) > 0', name='check_mood_name_not_empty'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_mood_id'), 'mood', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('profile_picture_url', sa.String(length=512), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('name IS NULL OR length(name) > 0', name='check_name_not_empty'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_user_active', 'user', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('journal',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('color', sa.Enum('RED', 'ORANGE', 'AMBER', 'YELLOW', 'LIME', 'GREEN', 'EMERALD', 'TEAL', 'CYAN', 'SKY', 'BLUE', 'INDIGO', 'VIOLET', 'PURPLE', 'FUCHSIA', 'PINK', 'ROSE', 'SLATE', 'GRAY', 'ZINC', 'NEUTRAL', 'STONE', name='journal_color_enum'), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('entry_count', sa.Integer(), nullable=False),
    sa.Column('last_entry_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('entry_count >= 0', name='check_entry_count_positive'),
    sa.CheckConstraint('length(title) > 0', name='check_title_not_empty'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_journal_user_archived', 'journal', ['user_id', 'is_archived'], unique=False)
    op.create_index('idx_journal_user_created', 'journal', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_journal_user_favorite', 'journal', ['user_id', 'is_favorite'], unique=False)
    op.create_index(op.f('ix_journal_id'), 'journal', ['id'], unique=False)
    op.create_table('prompt',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('text', sa.String(length=1000), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('difficulty_level', sa.Integer(), nullable=False),
    sa.Column('estimated_time_minutes', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint('difficulty_level >= 1 AND difficulty_level <= 5', name='check_difficulty_level_range'),
    sa.CheckConstraint('estimated_time_minutes IS NULL OR estimated_time_minutes > 0', name='check_estimated_time_positive'),
    sa.CheckConstraint('length(text) > 0', name='check_prompt_text_not_empty'),
    sa.CheckConstraint('usage_count >= 0', name='check_usage_count_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_prompts_category', 'prompt', ['category'], unique=False)
    op.create_index('idx_prompts_difficulty_level', 'prompt', ['difficulty_level'], unique=False)
    op.create_index('idx_prompts_popular', 'prompt', ['is_active', 'usage_count'], unique=False)
    op.create_index('idx_prompts_user_active', 'prompt', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_prompt_id'), 'prompt', ['id'], unique=False)
    op.create_table('tag',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.CheckConstraint('length(name) > 0', name='check_tag_name_not_empty'),
    sa.CheckConstraint('usage_count >= 0', name='check_usage_count_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_tag_user_name')
    )
    op.create_index('idx_tags_usage_count', 'tag', ['user_id', 'usage_count'], unique=False)
    op.create_index(op.f('ix_tag_id'), 'tag', ['id'], unique=False)
    op.create_index(op.f('ix_tag_name'), 'tag', ['name'], unique=False)
    op.create_table('user_settings',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('daily_prompt_enabled', sa.Boolean(), nullable=False),
    sa.Column('time_zone', sa.String(length=50), nullable=False),
    sa.Column('push_notifications', sa.Boolean(), nullable=False),
    sa.Column('reminder_time', sa.String(length=5), nullable=True),
    sa.Column('writing_goal_daily', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(length=20), nullable=False),
    sa.CheckConstraint("theme IN ('light', 'dark', 'auto')", name='check_theme_valid'),
    sa.CheckConstraint('writing_goal_daily > 0', name='check_goal_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('writing_streak',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_entry_date', sa.Date(), nullable=True),
    sa.Column('streak_start_date', sa.Date(), nullable=True),
    sa.Column('total_entries', sa.Integer(), nullable=False),
    sa.Column('total_words', sa.Integer(), nullable=False),
    sa.Column('average_words_per_entry', sa.Float(), nullable=False),
    sa.CheckConstraint('average_words_per_entry >= 0.0', name='check_avg_words_positive'),
    sa.CheckConstraint('current_streak >= 0', name='check_current_streak_positive'),
    sa.CheckConstraint('longest_streak >= 0', name='check_longest_streak_positive'),
    sa.CheckConstraint('longest_streak >= current_streak', name='check_longest_gte_current'),
    sa.CheckConstraint('total_entries >= 0', name='check_total_entries_positive'),
    sa.CheckConstraint('total_words >= 0', name='check_total_words_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_writing_streak_active', 'writing_streak', ['last_entry_date', 'current_streak'], unique=False)
    op.create_index('idx_writing_streak_last_entry', 'writing_streak', ['last_entry_date'], unique=False)
    op.create_index('idx_writing_streak_user_date', 'writing_streak', ['user_id', 'last_entry_date'], unique=False)
    op.create_index(op.f('ix_writing_streak_id'), 'writing_streak', ['id'], unique=False)
    op.create_table('entry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('content', sa.String(length=100000), nullable=False),
    sa.Column('journal_id', sa.Uuid(), nullable=False),
    sa.Column('prompt_id', sa.Uuid(), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('weather', sa.String(length=100), nullable=True),
    sa.CheckConstraint('length(content) > 0', name='check_content_not_empty'),
    sa.CheckConstraint('word_count >= 0', name='check_word_count_positive'),
    sa.ForeignKeyConstraint(['journal_id'], ['journal.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompt.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_entries_created_at', 'entry', ['created_at'], unique=False)
    op.create_index('idx_entries_journal_date', 'entry', ['journal_id', 'entry_date'], unique=False)
    op.create_index('idx_entries_prompt_id', 'entry', ['prompt_id'], unique=False)
    op.create_index(op.f('ix_entry_entry_date'), 'entry', ['entry_date'], unique=False)
    op.create_index(op.f('ix_entry_id'), 'entry', ['id'], unique=False)
    op.create_table('entry_media',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('entry_id', sa.Uuid(), nullable=False),
    sa.Column('media_type', sa.Enum('IMAGE', 'VIDEO', 'AUDIO', 'UNKNOWN', name='media_type_enum'), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('alt_text', sa.String(length=500), nullable=True),
    sa.Column('upload_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='upload_status_enum'), nullable=False),
    sa.Column('file_metadata', sa.String(length=2000), nullable=True),
    sa.Column('processing_error', sa.String(length=1000), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.CheckConstraint('duration IS NULL OR duration >= 0', name='check_duration_non_negative'),
    sa.CheckConstraint('file_size > 0', name='check_file_size_positive'),
    sa.CheckConstraint('height IS NULL OR height > 0', name='check_height_positive'),
    sa.CheckConstraint('width IS NULL OR width > 0', name='check_width_positive'),
    sa.ForeignKeyConstraint(['entry_id'], ['entry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_id', 'checksum', name='uq_entry_media_entry_checksum')
    )
    op.create_index('idx_entry_media_checksum', 'entry_media', ['checksum'], unique=False)
    op.create_index('idx_entry_media_entry_id', 'entry_media', ['entry_id'], unique=False)
    op.create_index('idx_entry_media_status', 'entry_media', ['upload_status'], unique=False)
    op.create_index('idx_entry_media_type', 'entry_media', ['media_type'], unique=False)
    op.create_index(op.f('ix_entry_media_id'), 'entry_media', ['id'], unique=False)
    op.create_table('entry_tag_link',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('entry_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entry.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entry_id', 'tag_id')
    )
    op.create_index('idx_entry_tag_link_tag_id', 'entry_tag_link', ['tag_id'], unique=False)
    op.create_table('mood_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('entry_id', sa.Uuid(), nullable=True),
    sa.Column('mood_id', sa.Uuid(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('logged_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entry.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mood_id'], ['mood.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_id')
    )
    op.create_index('idx_mood_logs_logged_date', 'mood_log', ['logged_date'], unique=False)
    op.create_index('idx_mood_logs_mood_id', 'mood_log', ['mood_id'], unique=False)
    op.create_index('idx_mood_logs_user_id_logged_date', 'mood_log', ['user_id', 'logged_date'], unique=False)
    op.create_index('idx_mood_logs_user_mood', 'mood_log', ['user_id', 'mood_id'], unique=False)
    op.create_index(op.f('ix_mood_log_id'), 'mood_log', ['id'], unique=False)
    op.create_index(op.f('ix_mood_log_logged_date'), 'mood_log', ['logged_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mood_log_logged_date'), table_name='mood_log')
    op.drop_index(op.f('ix_mood_log_id'), table_name='mood_log')
    op.drop_index('idx_mood_logs_user_mood', table_name='mood_log')
    op.drop_index('idx_mood_logs_user_id_logged_date', table_name='mood_log')
    op.drop_index('idx_mood_logs_mood_id', table_name='mood_log')
    op.drop_index('idx_mood_logs_logged_date', table_name='mood_log')
    op.drop_table('mood_log')
    op.drop_index('idx_entry_tag_link_tag_id', table_name='entry_tag_link')
    op.drop_table('entry_tag_link')
    op.drop_index(op.f('ix_entry_media_id'), table_name='entry_media')
    op.drop_index('idx_entry_media_type', table_name='entry_media')
    op.drop_index('idx_entry_media_status', table_name='entry_media')
    op.drop_index('idx_entry_media_entry_id', table_name='entry_media')
    op.drop_index('idx_entry_media_checksum', table_name='entry_media')
    op.drop_table('entry_media')
    op.drop_index(op.f('ix_entry_id'), table_name='entry')
    op.drop_index(op.f('ix_entry_entry_date'), table_name='entry')
    op.drop_index('idx_entries_prompt_id', table_name='entry')
    op.drop_index('idx_entries_journal_date', table_name='entry')
    op.drop_index('idx_entries_created_at', table_name='entry')
    op.drop_table('entry')
    op.drop_index(op.f('ix_writing_streak_id'), table_name='writing_streak')
    op.drop_index('idx_writing_streak_user_date', table_name='writing_streak')
    op.drop_index('idx_writing_streak_last_entry', table_name='writing_streak')
    op.drop_index('idx_writing_streak_active', table_name='writing_streak')
    op.drop_table('writing_streak')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_tag_name'), table_name='tag')
    op.drop_index(op.f('ix_tag_id'), table_name='tag')
    op.drop_index('idx_tags_usage_count', table_name='tag')
    op.drop_table('tag')
    op.drop_index(op.f('ix_prompt_id'), table_name='prompt')
    op.drop_index('idx_prompts_user_active', table_name='prompt')
    op.drop_index('idx_prompts_popular', table_name='prompt')
    op.drop_index('idx_prompts_difficulty_level', table_name='prompt')
    op.drop_index('idx_prompts_category', table_name='prompt')
    op.drop_table('prompt')
    op.drop_index(op.f('ix_journal_id'), table_name='journal')
    op.drop_index('idx_journal_user_favorite', table_name='journal')
    op.drop_index('idx_journal_user_created', table_name='journal')
    op.drop_index('idx_journal_user_archived', table_name='journal')
    op.drop_table('journal')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index('idx_user_active', table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_mood_id'), table_name='mood')
    op.drop_table('mood')
    # ### end Alembic commands ###
